language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.4

install: .travis/install-deps.sh

script:
- find . -name "*.sh" -exec shellcheck {} \;
- find . -name "*.sh" -exec bashate {} \;
- find . -name "*.py" -exec flake8 {} \;
- find ansible -name "*.yml" -exec ansible-lint -x 503 {} \;
- foodcritic chef/cookbooks
- cookstyle .
