- name: create assets folder
  file:
    path: "{{ assets_download_dir }}"
    state: directory
    mode: 0764
    recurse: true

- include: download-asset.yml
  with_items:
    "{{ assets_files + additional_assets_files | default([]) }}"
