chef_admin_username: operations
chef_admin_password: welcome
chef_admin_group: operators
chef_admin_first_name: admin
chef_admin_last_name: admin
chef_admin_client_key: /etc/chef/operations.pem
chef_admin_email: "operations@{{ cloud_domain }}"
chef_org_short_name: bcpc
chef_org_long_name: Bloomberg Clustered Private Cloud
chef_org_validator_pem: /etc/chef/validator.pem
chef_server_host: "{{ groups['bootstraps'][0] }}"
chef_server_ip: "{{ hostvars[chef_server_host][service][ip] | ipaddr('address') }}"
chef_server_fqdn: "{{ chef_server_host }}.{{ cloud_infrastructure_domain }}"
chef_server_url: "https://{{ chef_server_fqdn }}/organizations/{{ chef_org_short_name }}"
chef_server_package: "{{ 'chef_server' | find_asset(all_file_assets) }}"
