- name: create file server assets folder
  file:
    path: /var/bcpc/file-server
    state: directory
    mode: 0755
    recurse: true

- include: upload-file-server-file.yml
  with_items: "{{ all_file_server_assets }}"
