- name: set file fact
  set_fact:
    file: "{{ item.file_asset | find_asset(all_file_assets) }}"

- name: "upload file server asset: {{ file.name }}"
  copy:
    src: "{{ assets_download_dir }}/{{ file.filename }}"
    dest: "/var/bcpc/file-server/"
