- import_tasks: chef-workstation.yml
  become: true
  tags: [never,chef-workstation]

- import_tasks: generate-chef-environment.yml
  tags: [never,chef-workstation,generate-chef-environment,sync-chef]

- import_tasks: extra-cookbooks.yml
  tags: [never,chef-workstation,upload-extra-cookbooks]

- import_tasks: sync-chef.yml
  tags: [never,chef-workstation,sync-chef,upload-extra-cookbooks]
