- name: upload cookbooks
  synchronize:
    src: "{{ item }}"
    dest: "/var/bcpc/chef/{{ chef_org_short_name }}/"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--copy-links"
      - "--exclude=*.swp"
      - "--exclude=.git"
  with_items:
    - "{{ chef_cookbooks_dir }}"

- name: upload environments, roles and databags
  synchronize:
    src: "{{ item }}"
    dest: "/var/bcpc/chef/{{ chef_org_short_name }}/"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=*.swp"
      - "--exclude=.*"
  with_items:
    - "{{ chef_environments_dir }}"
    - "{{ chef_roles_dir }}"
    - "{{ chef_databags_dir }}"

- name: import data bags
  shell: |
    for data_bag in $(ls *.json); do
      knife data bag from file "{{ cloud_region }}" ${data_bag}
    done
  args:
    chdir: "/var/bcpc/chef/{{ chef_org_short_name }}/databags"
  changed_when: false

- name: knife upload org
  command: knife upload .
  args:
    chdir: "/var/bcpc/chef/{{ chef_org_short_name }}"
  changed_when: false
